name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: make up-detach
      run: make up-detach
      
    - name: make restart
      run: make restart
      
    - name: make down
      run: make down
      
    - name: make up-detach
      run: make up-detach
    
    - name: make clean
      run: make clean
    
    - name: make up-detach
      run: make up-detach
    
    - name: make re-detach
      run: make re-detach
      
    - name: make fclean
      run: make fclean
